### ISSUE TITLE
Match event order depends on the platform

### ISSUE THREAD

**Issue by heikki** [isaacs/node-glob#143]
I run into this when trying to figure out why gulp outputs files in [different order on windows](https://github.com/gulpjs/gulp/issues/687#issuecomment-64544815). This used to work with older version of gulp. Detective work pointed to this graceful-fs change: https://github.com/isaacs/node-graceful-fs/commit/08471b246bec73848b53e9ad4972f5fe02031805

If this was to be "fixed" now the most convenient and probably the only place would be in node-glob and it would be to sort each [readdir result](https://github.com/isaacs/node-glob/blob/c5313b5e3a5f5227617b40d8914a41d5dfc8c095/glob.js#L453):

`self._readdirEntries(abs, entries, cb)` -> `self._readdirEntries(abs, entries.sort(), cb)`

I run benchmarks to see what kind of performance penalty there is but couldn't see anything consistent. The following is three run average and numbers are: [before fix] -> [after fix] (percentage change):

```
Node statSync and readdirSync timing:

    real 1.681 -> 1.633 (-2.9%)
    user 1.138 -> 1.123 (-1.3%)
    sys  0.530 -> 0.528 (-0.4%)

Node glob.sync timing:

    real 3.921 -> 3.879 (-1.1%)
    user 3.314 -> 3.284 (-0.9%)
    sys  0.647 -> 0.635 (-1.1%)

Node glob async timing:

    real 7.752 -> 7.816 (+0.8%)
    user 7.461 -> 7.515 (+0.7%)
    sys  1.501 -> 1.524 (+1.5%)
```

**Comment by isaacs** [comment]
@contra @heikki I'm sorry to be the bearer of bad news.

It turns out that sorting the readdir results isn't actually enough of a fix, and in fact, it *can't* be reliably fixed in the general case without some truly awful things.

Consider this:

```
a
├── b/
│   └── z/
└── c/
    └── z/
```

If you glob for `a/*/z` then it does the first readdir on the `a/` dir.  Some platforms this returns `['b','c']` and others, `['c','b']`.  So, we sort it.

Then, for each of those two dirs, *in parallel*, it does a `readdir` to see if there's a `z` inside.  They'll both hit the thread pool at effectively the same time, just a few ns off.  But sometimes, `readdir('a/c')` will return before `readdir('a/b')`, so even though we sort every readdir, we still get `a/c/z` before `a/b/z`.

To truly fix this, we'd have to somehow sort the `readdir` responses *and also* sort the return processing from each child branch to manage the order that they return in.  That's way beyond my threshold for complexity.  A simpler approach would be to serialize the processing of each child dir, but then we'll be leaving a lot of performance on the table (like, 4x in some cases).

With that in mind, I'm going to revert this "fix", because it adds complexity and CPU cycles for no benefit.

You'll just have to handle out-of-order results.  They are sorted in the final tally, though, so you can either have them sooner (and maybe out of order), or all at once (and sorted).  Trade-off appropriately for your use case, I guess.

**Comment by heikki** [comment]
@isaacs Ok, thanks for info. Have to figure out alternative.
