### ISSUE TITLE
Does Glob work in Grunt on Windows?

### ISSUE THREAD

**Issue by shukriadams** [isaacs/node-glob#160]
The following code works fine for me when executed in NodeJs :

    var glob = require('glob');
    glob("**/*.js", null, function (er, files) {
      	for (var i = 0 ; i < files.length ; i  ++){
  	    	console.log(files[i]);
 	   }
    });

It traverses all child folders below the execute folder and returns all .js files.

But when I put that code into a Grunt plugin, I get no hits. When I change my search string to ".js*" my Grunt plugin finds all .js files in the Grunt execute folder, so something appears to be working; folder traversing just seems to broken somehow. 

I've resorted to using https://www.npmjs.com/package/glob-whatev as a Glob alternative, that works, and that projects also mentions that the Glob + Grunt + Windows combination doesn't work for some or the other reason. Any chance this break will be fixed? Thanks.

**Comment by isaacs** [comment]
Well, as you say, glob is working fine.

I am not the maintainer of Grunt, and have no idea exactly what it's doing with glob internally.  node-glob-whatev is over 2 years old, and LOTS of bugs have been fixed since then, both on Windows and Unix.

I'd try posting the bug over on grunt's issue tracker.  If it turns out glob is doing the wrong thing, then we can take a look at it.
