### ISSUE TITLE
having trouble with negation patterns

### ISSUE THREAD

**Issue by lfender6445** [isaacs/node-glob#165]
Given the following files, how would i write negation pattern to exclude index.html and js/main.js?

- index.html
- js/lib.js
- js/main.js

```
glob('!(index.html|js/main.js)**/*', function(e,files){console.log(files)}) # => []
```

**Comment by isaacs** [comment]
Try this:

```javascript
glob('**', { ignore: [ 'index.html', 'js/main.js' ], nodir: true }, console.log)
```

Negative extglob patterns like `!(foo)` cannot contain slashes.  So, another approach might be to do something like one of these, depending on how many *other* files are in there that youer' trying to exclude.

```javascript
> glob.sync('!(*.html)/!(main.js)', { nonegate: true })
[ 'js/lib.js' ]
> glob.sync('js/!(main.js)', { nonegate: true })
[ 'js/lib.js' ]
> glob.sync('js/!(main.js)')
[ 'js/lib.js' ]
```

(Note that the `nonegate` is required for now to interpret the first part as a negative extglob section rather than a fully negated pattern.  The next major release will deprecate using negated patterns, in favor of using ignores instead.)

**Comment by ilanbiala** [comment]
@isaacs does `ignore` accept globs as well?

**Comment by isaacs** [comment]
@iLanbiala yes it does.

**Comment by OliverJAsh** [comment]
> Negative extglob patterns like !(foo) cannot contain slashes

Can we add docs for this in the glob primer?
