### ISSUE TITLE
Please Help: Changelog

### ISSUE THREAD

**Issue by isaacs** [isaacs/node-glob#179]
People have requested a changelog.

But I don't want to write one by hand.

Please add a script that does this, and make it easy to run automatically.

**Comment by YuriSolovyov** [comment]
something like https://github.com/rvagg/changelog-maker ?

**Comment by eddiemonge** [comment]
Would you be open to having a commit message format for every commit?

**Comment by jimf** [comment]
> "But I don't want to write one by hand."

Write or maintain?

**Comment by charlierudolph** [comment]
If you want to have a script that does it automatically, you need have each commit in a specific format. 

If you don't want to do that, what I've done in other projects is before each release look through the commits since the last release and determine which you should let users know about (interface changes, bug fixes, new features). You could use the following command to get the commits since the last release: `git log <last-version-tag>..master`.

Keeping a changelog is very useful for users who would otherwise need to look through the commits and changes since the last release. A maintainer should have much better knowledge of this and be able to determine the relevant changes much more easily.

I doubt backfilling the changelog to the initial version is all that useful anyway, so just starting one now and adding to it with each new release would be greatly appreciated.
