### ISSUE TITLE
Absolute ignore doesn't work

### ISSUE THREAD

**Issue by feross** [isaacs/node-glob#189]
Absolute ignores are not working correctly.

Here's an example using the test fixtures:

```js
glob('**', {
  ignore: [ '/abcdef', '/abcdef/**' ],
  cwd: 'a',
  root: path.resolve('a')
})
```

This still finds "abcdef", "abcdef/g", and "abcdef/g/h".

**Comment by feross** [comment]
Here's a PR with a failing test: https://github.com/isaacs/node-glob/pull/190

**Comment by isaacs** [comment]
This is tricky.

The idea for ignores is "exclude all potential matches which would be returned by a search for any of the ignore patterns".  It's not "exclude all potential matches which refer to files that would be found by any of the ignore patterns".

So, for example, `/a/b/c` *doesn't* return `a/b/c` as a match, even if that file exists.

```
> matches = glob.sync('tmp/x/y/z', { cwd: '/' })
[ 'tmp/x/y/z' ]
> ignore = glob.sync('/tmp/x/y/z', { cwd: '/' })
[ '/tmp/x/y/z' ]
> require('array-intersection')(matches, ignore)
[]
```

If we tell it to give us the realpath value, then it'll do the right thing:

```
> real = glob.sync('tmp/x/y/z', { cwd: '/', ignore: '/private/tmp/x/y/z', realpath: true })
[]
```

That's because the `real` option makes it so that you only get absolute paths.

In order to satisfy the test in #190, we'd have to add a `path.resolve` and double-check any non-absolute results.  And I'm not sure it's really the ideal semantics, but it's worth discussing the trade-offs.  At least, it's a breaking change.

Regarding feross/standard#116, it's worth noting that `glob('**', { ignore: gitignoreLines })` is not quite what an ignore file does, anyway.  The patterns and the file names all need to be mounted on the directory where the ignore file lives.  You could check out https://github.com/npm/fstream-ignore if you want to use the same file selection logic that npm uses for ignore files in packages.
