### ISSUE TITLE
top-level like function definition under the function scope

### ISSUE THREAD

**Issue by obastemur** [isaacs/node-glob#202]
Actual issue is : `functions can only be declared at top level or immediately within another function.` (message from v8 under strict mode)

There are some next, done etc. function definitions (under another functions scope) raising this problem under glob.js. I can happily contribute to the fix ?

**Comment by isaacs** [comment]
I don't see the error you're describing.  How are you getting this?

**Comment by obastemur** [comment]
Sorry, don't remember the module depending on `node-glob`. Honestly, I don't even remember which project was that. We had to manually edit glob.js and move function definitions on top. 

for example;
```
Glob.prototype._stat = function (f, cb) {
  var abs = this._makeAbs(f)
  ...
  ...
  var self = this
  var statcb = inflight('stat\0' + abs, lstatcb_)
  if (statcb)
    fs.lstat(abs, statcb)

  function lstatcb_ (er, lstat) {
    if (lstat && lstat.isSymbolicLink()) {
      // If it's a symlink, then treat it as the target, unless
      // the target does not exist, then treat it as a file.
      return fs.stat(abs, function (er, stat) {
        if (er)
          self._stat2(f, abs, null, lstat, cb)
        else
          self._stat2(f, abs, er, stat, cb)
      })
    } else {
      self._stat2(f, abs, er, lstat, cb)
    }
  }
}
```

The way `lstatcb` defined is not ECMA `friendly`. The scope issue becoming even more stricter with ES6 classes. Hopefully not but if putting up a sample code that throws an error is the only way for a change, I will try to find some space for it.

**Comment by isaacs** [comment]
That's totally fine in ECMAScript strict mode.  Function expressions may be in conditionals, just not function declarations.

For example, this would throw:

```
'use strict'

if (true) {
  function foo() { return 1 }
}
```

But this is totally fine:

```
'use strict'

if (true) {
  var foo = function foo() { return 1 }
}
```

**Comment by obastemur** [comment]
Although conditional scope is yet another issue, the piece of code Ive shared (from glob.js) exactly samples the problem you have shared.

That's the reason I had opened this issue. So, are you planning to apply it to glob or carry the functions to top?

**Comment by isaacs** [comment]
You are getting confused about the difference between "function declaration" and "function expression".

A function used as a callback like `fs.readdir(dir, function (er, entries) { ... })` is not a function declaration.  It is a function expression.

Furthermore, the issue in V8's strict mode where it says "functions can only be declared at top level or immediately within another function", is in fact not compliant with the ES6 specification.  The actual rule is that function declarations inside of blocks in strict mode are local to the block.  Io.js and future versions of Node have newer versions of V8 which observe the ES6 specification in this regard.  Observe: https://gist.github.com/isaacs/ea2b667d7336b64843e1

No, I will not be changing node glob.  It functions properly in strict mode, both in old (incorrect) versions of V8 as well as new (correct) versions of V8.  The error you cite is not applicable in either case, because these are function expressions, not function declarations.

**Comment by obastemur** [comment]
scope discussion aside, once again hit to same problem. I've just realized that the issue is no longer the case on master or latest glob on npm. The problem looks like happening on older version.

Here is the sample code to reproduce:

save into `test.js`
```
require('jasmine');
```

npm install jasmine

run:
```
node --use-strict test.js
```

result
```
node_modules/jasmine/node_modules/glob/glob.js:323
    function next(exists, isDir) {
    ^^^^^^^^
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
```

node version: 0.12.6

solution:
update the glob under jasmine to latest. 

I will be opening this issue on it's place (jasmine). 

Thanks for the details and discussion.
