### ISSUE TITLE
Can't get !(pattern) to work

### ISSUE THREAD

**Issue by sieira** [isaacs/node-glob#224]
I'm trying to do this for my grunt clean script:

`"{**/node_modules/!(grunt*)/,**/bower_components}"`

So I delete every node and bower module except grunt and its contrib.

Blob is returning (among many others) `node_modules/grunt/node_modules/hooker/`

I'm clearly misunderstanding how the operator work...

**Comment by isaacs** [comment]
Let's simplify this, because clearly it's not the second part of the pattern that's matching, since it doesn't end in `bower_components`.

`**/node_modules/!(grunt*)` will match `node_modules/grunt/node_modules/foo` because the `**` matches `node_modules/grunt/node_modules` and then `foo` is not `grunt*`, so there you go.  The pattern will match any thing containing `node_modules` that doesn't *end in* `grunt*`, so this will match most of grunt's deps.

I think what you probably want is to drop the `**`, and just use this: `node_modules/!(grunt*)`, or combined with the `bower_components`, `{node_modules/!(grunt*),**/bower_components}`.

**Comment by sieira** [comment]
Ok, this was it:

`{node_modules/!(grunt*),!(node_modules)/**/node_modules/,**/bower_components}`

it can surely be improved, because I only need the higher level node_modules on each sub directory,and only keep grunt modules on the highest, but I will leave a TODO and think about it another day.

I know this was not the best place to ask this kind of question. Thank you for your kind answer.
