### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by callumlocke** [isaacs/node-glob#228]
Would you accept a PR to add promise support to node-glob?

```js
glob("**/*.js", options).then(function (files) {
  // ...
}, function (error) {
  // ...
})
```

If so, let me know which approach you'd prefer:

Option 1 (major version bump): remove callback API, and just return a promise
Option 2 (minor version bump): keep the existing callback API, and also return a promise

Personally I'd prefer option 1 for simplicity.

(I would suggest using [pinkie-promise](https://github.com/floatdrop/pinkie-promise) either way, which seems to be the best option for using real Promises where available and switching to a polyfill where necessary.)

**Comment by isaacs** [comment]
Not really that interested.  Passing in a function works fine, and you can wrap it in a promise if you really need to.

**Comment by a-x-** [comment]
ooh...

i have my own promise wrapper:

```js
module.exports = (globPattern, onFile) => {
    const occurences = []
    return new Promise((res, rej) =>
        glob(globPattern, file => {
            const result = onFile(file)
            result !== undefined && occurences.push(result)
        })
        .end(() => res(occurences))
}
```

I want to make npm package
but maybe anybody already has one?

**Comment by Milewski** [comment]
@a-x-  why do u `result !== undefined ` ?

**Comment by a-x-** [comment]
i forget

**Comment by syuilo** [comment]
Promises is better than callbacks

**Comment by popomore** [comment]
Maybe you can use  https://github.com/node-modules/mz-modules

**Comment by zzarcon** [comment]
Hi @isaacs thanks for the library!

Do you think we can re-open this? I think its worth it to add Promise support as first class citizen :)

**Comment by gauntface** [comment]
+1 for promise support.

**Comment by penx** [comment]
+1 by association for async await plox

**Comment by devnieL** [comment]
+1 for async/await support with promises

**Comment by xipheCom** [comment]
I am here because i can use promises /async...await out of the box. Would be great if you can add it.

**Comment by FallingSnow** [comment]
For the time being you can
```js
const util = require('util');
const glob = util.promisify(require('glob'));
```

**Comment by abdulhannanali** [comment]
Or you can use https://github.com/mrmlnc/fast-glob It seems fine for  most use cases and claims to be faster.

**Comment by yuta0801** [comment]
Adding promise is really easy. Just return promise wrapper around itself when the function executed without callback. (but this way can't refer to the Glob instance returns by the function)

```js
function glob (pattern, options, cb) {
  if (typeof options === 'function') cb = options, options = {}
  if (!options) options = {}

  if (options.sync) {
    if (cb)
      throw new TypeError('callback provided to sync glob')
    return globSync(pattern, options)
  }

  // added block <<
  if (!cb) return new Promise(function (resolve, reject) {
    glob(pattern, options, function (er, files) {
      if (er) reject(er)
      else resolve(files)
    })
  })
  // >>

  return new Glob(pattern, options, cb)
}
```

Now Promise is supported by [many versions](https://node.green/#ES2015-built-ins-Promise) and used many to avoid the callback hell.
It is good to let the user promisify, but I think the library itself supports the promise will increase the value of the library.

**Comment by clytras** [comment]
If the user does not pass a callback function, then return a promise. This is from 2015 and we're at 2020 and really callbacks are _an old way to do_.

**Comment by haliaeetus** [comment]
> If the user does not pass a callback function, then return a promise. This is from 2015 and we're at 2020 and really callbacks are _an old way to do_.

I've settled on another module instead: https://github.com/sindresorhus/globby

**Comment by slikts** [comment]
This issue (specifically, its resolution) has aged like milk.

**Comment by cbartondock** [comment]
Agreed - few people today would prefer callbacks to promises. Maintainers have rejected two PR's for a promise api.

**Comment by b-zurg** [comment]
Sometimes GitHub issues are hilarious. This is one of them. Promises are one of the only decent things to happen to JavaScript.  Amazing that something so... sensible would be rejected.

**Comment by ruifortes** [comment]
You can't bother the Master with this pety requests!!! :-)

**Comment by flying-sheep** [comment]
> I've settled on another module instead: [sindresorhus/globby](https://github.com/sindresorhus/globby)

My eyes went immediately to `index.d.ts` and I knew you pointed me to something good. Thank you!

**Comment by gotham8x** [comment]
> > I've settled on another module instead: [sindresorhus/globby](https://github.com/sindresorhus/globby)
> 
> My eyes went immediately to `index.d.ts` and I knew you pointed me to something good. Thank you!

Sorry for bumping this post, but I just want to share my thoughts. `sindresorhus` made a lot useful node packages, but I and many others don't like his breaking changes recently. He have ported all his popular packages to pure ES Module which are not compatible with many projects. As a result, we have to port our projects to ES module or stay on those outdated packages!

**Comment by isaacs** [comment]
I'm going to lock this thread just to make sure this is the final word on this issue.

When I get around to it, I'm going to refactor node-glob to be a hybrid module written in TypeScript, with a promise based API.  I've been doing that for all my node packages. In the last year, I've updated node-lru-cache, minimatch, and a bunch of others. This module needs quite a bit of TLC, and its number hasn't come up yet.  But I am getting around to it.  First I had to update minimatch, and I've been busy with some next-gen node-tap work.  But all of this is only fitting into a tiny sliver of my available time.

I don't get paid to work on OSS (other than the Tier node sdk, of course).  I have a kid, and a life, and a job.  This is a hobby, one that I wish I could devote more time to than I do, but still a hobby.  I don't stress over it.  I'll get to it when I get to it.

If you want to use another glob implementation in the meantime, ok, cool, go for it.  The benefit of this one (or maybe the drawback, depending on who you ask) is that it matches the Bash pattern matching behavior about as closely as it is possible to in JavaScript. But there are others that get more attention, have been updated more recently, etc. Taking shortcuts on correctness can sometimes result in greater speed, and maybe that's a benefit you care about more than matching shell behavior as closely as possible.  More power to you.

If you'd like to get me to prioritize this issue ahead of other things going on in my life, and treat it like my job, then you can do that with money, because like most of us, I am indentured to the capitalist machine in order to live and provide for my family.  My time is not cheap, but if you are in a hurry, that's the way to get me moving sooner.  https://izs.me/hire or https://github.com/sponsors/isaacs or you can email me at <i@izs.me> and we can work something out.

**Comment by isaacs** [comment]
Also, wth people, this issue is from 2015, that was a perfectly fine answer back then 😂

OSS is crazy sometimes, I swear.
