### ISSUE TITLE
Should error if globbing inside with a path that is not a directory

### ISSUE THREAD

**Issue by willm** [isaacs/node-glob#235]
I'm raising this because it's been the result of a 2 day bug hunt found through many libraries with a very vague error at the end which could have been avoided

assuming you have a directory `/testDir` containing `file.txt`. If you run:

```
glob('**/*.txt', { cwd: '/testDir/file.txt'}, function (err, dir) {
  console.log(err, dir);
});
```

you get: `null, []`

Should err not be something like `new Error('Type error, cwd must be a directory')` So that you know that it's a programmer error? I'm happy to make a pull request for this if you are happy with this suggestion.

**Comment by isaacs** [comment]
Fixed on master.  Had to bump the major, since this is raising a new error, and so it might cause a currently-working program to break.

Tough call, since it feels like a "bugfix" rather than a breaking change, but I've learned to err on the side of being overly cautious when it comes to raising errors for things that were previously allowed, even if they were incorrectly allowed.
