### ISSUE TITLE
Add support to pass in fs interface

### ISSUE THREAD

**Issue by ghost** [isaacs/node-glob#280]
I enjoy node-glob, but I need its use on a virtual file system which is separate from the node fs, but with the same interface. If we modify fs.realpath and add in a fs parameter in the options which falls back to the default native fs t should be quite easy

**Comment by erikkemperman** [comment]
That would be exactly what I was looking for! Currently [`vinyl-fs`](https://github.com/gulpjs/vinyl-fs) is being updated to split off a module for use by other vinyl adapters, [`vinyl-prepare`](https://github.com/gulpjs/vinyl-prepare). With any luck it'll be in Gulp 4.

It would be great if implementers of custom vinyl adapters, such as purely in-memory ones, would not have to do their own globbing (or disallow glob patterns completely) -- but instead just provide the needed subset of `fs` calls as an option.

At this time, our call to glob can't be transplanted to `vinyl-prepare` because of its file system access, but I think it should be.

@isaacs I'd be willing to spend some time on a PR, unless of course you don't like the idea to begin with?

**Comment by erikkemperman** [comment]
Come to think of it, maybe folks would like to use `graceful-fs`, that would also be easy with something like the above in place.

**Comment by erikkemperman** [comment]
@Auxolust I've submitted a [PR](https://github.com/isaacs/node-glob/pull/285) that would address my use case... And yours, I believe?

Sorry about the repeated references above, I cleaned up the accompanying test a little bit and force-pushed to override the previous commit. But since it already had the issue number in there, this happened.

**Comment by blond** [comment]
> Come to think of it, maybe folks would like to use graceful-fs, that would also be easy with something like the above in place.

@erikkemperman there are reasons to use `graceful-fs`: #299

**Comment by millette** [comment]
I've got a [small patch](https://github.com/millette/node-glob/tree/opt-fs) too so I can use glob with dat and [hyperdrive](https://github.com/mafintosh/hyperdrive) and it seems to work for me so far. Basically, I can now use glob like this:
```
// dat.archive is a hyperdrive instance
glob('*', { cwd: '/', fs: dat.archive), (err, files) => {
  // and voilà
})
```

**Comment by martinheidegger** [comment]
I was looking at this issue exactly because of how to use it with hyperdrive and plan to use the small patch by @millette . Total :+1: by me for having this. Would it be okay to publish a PR based on this prior work?

**Comment by ajafff** [comment]
To anyone who also wants to use a custom `fs` implementation without patching `glob` as described above: I created a package that allows intercepting file system access: https://www.npmjs.com/package/glob-interceptor

Caveat: it only works with synchronous IO.

**Comment by resistdesign** [comment]
Wow, this has been here for a while.

**Comment by isaacs** [comment]
If this is added to https://github.com/isaacs/path-scurry, then glob will pass the requisite options along.  Glob doesn't actually touch the file system directly any more, everything goes through PathScurry.
