### ISSUE TITLE
Is it possible to specify a maximum depth?

### ISSUE THREAD

**Issue by staff0rd** [isaacs/node-glob#296]
For example if i have;

```
\some\path\
\another\directory\
\some\longer\path\
\an\even\longer\path\
```

Is there a way to specify a maximum depth that the tree will be traversed, such that executing glob against the above would only return the first two paths, being 2 deep?

**Comment by bluelovers** [comment]
need this

**Comment by isaacs** [comment]
For two, the easiest way would be to use a pattern like this: `glob(['*', '*/*'])` and it'll only go two directories deep.  Obviously this isn't so great when you want to set the limit to something like 100 folders deep.

Currently, there's no way to set a maximum depth for patterns like `**` though, no.  It would be a bit tricky to do, but not entirely impossible.  I'd approach it by first adding some concept of a "depth" field in PathScurry, which might actually have other benefits anyway.

**Comment by isaacs** [comment]
Now that PathScurry tracks the depth, I'm thinking it might be possible to do something like:

```
glob(pattern, { maxDepth: <some number> })
```

which would only go as deep as the depth of the current working directory, plus the number specified.

Would it be worthwhile to set a _minimum_ depth as well?  For example, to prevent absolute patterns or anything starting with `..`?

This definitely has a few edge cases, because we translate `../**/x/x` into the combined patterns `../x/x` and `**/x/x`, since it's equivalent and shaves a factor off of the combinatorial explosion.  So if you set `minDepth: 0`, then it would prevent the first part, but not the second.  But a pattern like `../x/y/z`, run in `x`, would not return anything, because it'd refuse to walk the parent directory.  So that's a little weird.

**Comment by isaacs** [comment]
Also, would minDepth prevent the _walk_ or just the _match_? 🤔 

Like, in this case: `glob('/a/b/c/d/**', { cwd: '/w/x/y/z', minDepth: 4 })`

Would that match all the files in `/a/b/c/d`, because they're all above the depth of 4, or would it _not_ do that, because to do that it has to walk to `/a` and that's depth 1?

And if it _wouldn't_ match anything, what about this?  `glob('/a/b/c/d/**', { cwd: '/a/b/c/d', minDepth: 4 })`

I think it's probably simpler to just say it limits maximum depth only, and prevents both the walk and the match.  So:

```js
glob('../**', { cwd: '/a/b/c', maxDepth:2 })
```

would find `/a/b` (at relative depth -1), and `/a/b/c/d/e` (relative depth 1) and would match `/a/b/c/d/e/f` but not walk over its children.
