### ISSUE TITLE
CLI Tooling

### ISSUE THREAD

**Issue by nruhe** [isaacs/node-glob#320]
#305 referenced this a couple months back. While the use case is uncommon, I've found myself writing multiple npm scripts that require selections of files based on some sort of path parameter. The ideal solution would be to support the ability to take a node-glob since most JS engineers are familiar with the minimatch implementation and because of its wide use in existing JS tooling. Sadly, there isn't a good out-of-the-box solution for being able to utilize it directly via CL and shell scripts. 

Is adding CL support something you think fits within the scope and goals of this library, and if so, would it be worthwhile for me to open a PR against the library with that functionality added?

**Comment by isaacs** [comment]
Probably the command-line specific stuff shouldn't be in this library.  A lot of cli stuff does use node-glob to parse path options, especially since the shell doesn't do that for you on windows.

What would you want to add here?

**Comment by nruhe** [comment]
@isaacs What I'm hoping for is a way to use it to generate my file lists so I can pipe them to other commands inside of my package.json npm run scripts. Doing that here would require adding the bin property for node-glob inside of package.json and writing an additional interface file, sort of like how [ESLint](https://github.com/eslint/eslint) does it (check their package.json and bin folder). Then it would be possible to do things like: `scripts: { my_npm_run_script: 'glob "**/*.js" | a_command' }`. Thoughts?

**Comment by igalic** [comment]
so, i just hit this exact wall — trying to run scripts thru npm on different (CI) platforms, and, naïvely assumed that:

```json
  "scripts": {
    "mdlint": "markdownlint *.md apps/*/*.md"
  }
```

would already resolve correctly (for windows).
but apparently our wrapper needs a wrapper 😅

**Comment by isaacs** [comment]
I _really_ don't want to add a cli to this library.  http://npm.im/glob-cli exists.

**Comment by antitoxic** [comment]
@isaacs Actually the packages you mentioned are updated 9 years ago and 6 years ago. I think you know they are not really an alternative to `node-glob`.

I literally spent 1 hour and couldn't find a decent globing/find npm package with CLI.

What are your concerns about adding a CLI? Path expanding in the command prompt? Something else?

**Comment by isaacs** [comment]
@antitoxic hmm, that is a pretty good point. I guess adding a cli is fine. What's the api you'd like to see?

I'd like to avoid adding any deps for this, but a simple glob expander until could be handy I guess.

**Comment by isaacs** [comment]
I think you probably want something that will do more than just `find`.  Because it's not like `markdownlint $(glob *.md apps/*/*.md)` or `glob *.md apps/*/*.md | xargs markdownlint` will work on windows either, because it doesn't have `xargs` or `$()`.

What about something like this?

```ts
#!/usr/bin/env node
import { globSync } from 'glob'
import { spawnSync } from 'node:child_process'
const cmd = process.argv[2]
const args = process.argv.slice(3)
  .map(a => globSync(a))
  .reduce((set: string[], a) => set.concat(a), [])
const result = spawnSync(cmd, args, {
  stdio: 'inherit',
})
if (result.exitCode) {
  process.exitCode = result.exitCode
} else if (result.signal) {
  process.kill(process.pid, result.signal)
  setTimeout(() => {}, 200)
}
```

Then you could run `glob markdownlint *.md apps/*/*.md`.  On cmd or powershell, it'd expand the args, and on bash, it'd just be a no-op, since the args would already be expanded.

Of course, this gets weird if some of the filenames have special glob characters.  For example, if you had a file like `app/routes/[id].tsx`, then it'd be expanded by bash, and then try to expand it in glob, and would match `app/routes/i.tsx` and `app/routes/d.tsx`, which is not what you want.

I'm not really aware of a surefire way to _know_ whether we've been executed in cmd.exe vs bash (process.platform isn't reliable there, because Windows machines have bash now, and lots of people use it as their shell).

Re-opening, if anyone wants to adapt that code above into a PR and add some way to check for the executing shell (maybe just look at `process.env.SHELL` or `process.env.BASH_VERSION` or something?) that'd be lovely. (Tests and docs also nice.)

**Comment by isaacs** [comment]
Maybe that could be called `globexec`, and there could be another bin that _just_ outputs the matches? I guess you could also wrap them in quotes, and then it'd work the same on both systems.

**Comment by isaacs** [comment]
I have a spike of this in progress, but I want to have a `--cmd -c <exec command>` option that would get all the expanded globs as arguments (if no command set, then it just writes them all to stdout).

To do that, I wanted to use `foreground-child`, and that uses `signal-exit`.  Both of which are super dated and not hybrid TS, so they needed to be rewritten first. Which I would have had to get to anyway as part of the tap 18 project, so it's all good, but they're blockers for this as well.

Signal-exit is done and shipped, foreground-child just needs a few more tests to cover a new expansion to the interface. Iit'll now let you modify the parent process exit status, or avoid exiting entirely, which I've wanted a few times in the past, but was too onerous to do in the previous design). Should get to this pretty soon.

**Comment by isaacs** [comment]
I think the main caveat for usage will be that you _really_ want to quote the arguments if you're using this cross platform.

Imagine you have a file like `app/routes/foo/[id].ts`, and you do `glob app/routes/**/*.ts`.  On posix shells, it will expand the globs in the command line before calling `glob`, so it'll run `glob app/routes/[id].ts app/routes/foo/[bar].ts`, try to expand those `[]` expressions, and not find any matches.

One possible option would be to bring back the `nullglob` option.  Right now, that's not supported, and the use cases for it for anything _other than_ shell arguments are pretty minimal.  But then, if `app/routes/[id].ts` doesn't match anything, it'll use that exact string.  The hazard, of course, is that if you _do_ have something that matches, like `app/routes/i.ts` or `app/routes/d.ts`, then it'll still do the wrong thing.

Yet another approach would be a sort of "prefer exact match" option.  So anything it gets as an argument that _is_ an existing path on the filesystem, it'll just use that and not expand it.  That might be the ideal default, in fact, in which case there ought to be a `--no-prefer-exact-match` option to say "No, really, I know that's a real thing, but I actually want you to try to expand _all_ of these as glob patterns no matter what".

**Comment by isaacs** [comment]
"Prefer exact match" is a bit tricky, because eg `"*"` is a valid filename on posix systems, which is also matched by the `*` pattern.  So you could probably footgun yourself if you did `touch '**'` in your project.  But maybe that's a weird enough thing to do that we can just document it as a caveat and be done with it.
