### ISSUE TITLE
Cannot find module 'glob' in Node 4

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [isaacs/node-glob#321]
Failing job in Node 4: https://travis-ci.org/automutate/automutate/jobs/202870830
Passing jobs in 5-7: https://travis-ci.org/automutate/automutate/builds/202870826

Is there a minimum Node version supported by node-glob?

**Comment by isaacs** [comment]
> Is there a minimum Node version supported by node-glob?

Yes, but it's 0.10 :)

If I had to guess, what's happening is that some module is requiring `glob`, but isn't listing it as a dependency or peer dependency.  But, since some _other_ module in your tree requires glob, it "works by accident" in npm version 3 and above, because of tree-flattening.

Run `npm i glob -S` in your project and see if that fixes it.

**Comment by JoshuaKGoldberg** [comment]
Cool, thanks for the fast response! It's a dev-dependency and I must have forgotten to `-D`. 😄
