### ISSUE TITLE
Cannot set property '_fs' of undefined

### ISSUE THREAD

**Issue by glortho** [isaacs/node-glob#348]
When I call `glob('/my/dir/**/*.js', (err, results) => console.log(results))` I get:
```
Cannot set property '_fs' of undefined

   34 |var fs = require("fs");
   35 |var pathUtil = require("path");
   36 |var globToRegExp = require("glob-to-regexp");
   37 |var async = require('async');
   38 |
 > 39 |function Finder(fs) { this._fs = fs || this._fs; }
   40 |Finder.prototype.__proto__ = EventEmitter.prototype;
   41 |Finder.prototype._fs = fs;
   42 |
   43 |Finder.prototype.find = function (path, pattern, type, foundCallback, doneCallback) {
   44 |  var self = this;

   at Finder (.../node_modules/node-glob/index.js:39:32)
```
This is with node v8.0.0 on mac os 10.11.6. Has anyone seen this also?

**Comment by narayananramu** [comment]
Hi,

I faced the same error when I was playing with Vueify + Browserify and Gulp, here was my workaround

Instead of 

`var glob = require('node-glob');`

I used glob

`var glob = require('glob');`

Try this

`new glob('/my/dir/**/*.js', (err, results) => console.log(results))`

This workaround worked for me on macos 10.12.6 and node v8.5.0

**Comment by millette** [comment]
The [npm package node-glob](https://github.com/Crafity/node-glob) is a whole other implentation.

**Comment by codinggirl** [comment]
Yes, we should require `glob` instead of `node-glob`. This is not the project's issue.

```js
const glob = require('node-glob')

glob('/my/dir/**/*.js', {}, (err, results) => console.log(results))
```

**Comment by isaacs** [comment]
No longer relevant on v9.
