### ISSUE TITLE
Sort files via date modified

### ISSUE THREAD

**Issue by rohithkd** [isaacs/node-glob#353]
Currently glob is sorting via alphabetical name order. Is there any way to sort it based on modified file date?

**Comment by isaacs** [comment]
There's no way to do this without statting the files and sorting them yourself, I'm afraid.

This is a good argument for bringing back the `stat: true` option, and perhaps teaching PathScurry to keep _all_ the metadata retrieved from a stat, instead of just the Dirent bits.

If those two things happened, you'd be able to do this:

```ts
import { glob } from 'glob'
export const globSortedByDate = async (pattern, options = {}) => {
  const results = await glob('./blah/**', { ...options, withFileTypes: true, stat: true })
  return results.sort((a, b) => a.mtime - b.mtime).map(p => p.fullpath())
}
```
