### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by hexray-newbee** [isaacs/node-glob#375]
when globbing 600, 000 files with deep of 5 to 6 subfolders.

**Comment by Yqnn** [comment]
It's due to the way this library works: each time a file is found, it's added inside several Objects (`this.matches` , `this.cache` and `this.statCache` in [glob.js](https://github.com/isaacs/node-glob/blob/master/glob.js) ), using a significant amount of memory.
Disabling stats with `stat: false` option may help a bit to reduce the memory footprint.

Bit I guess it's better to use something else to handle huge filesystems.

**Comment by cmawhorter** [comment]
i was hitting this. if you are too, this may or may not be a workaround for you:

```ts
import { createInterface } from 'readline';
import { spawn } from 'child_process';

const dir = '/path/to/parent'; 
const cmd = spawn('find', ['.', '-type', 'f', '-name', 'someprefix*'], {cwd: dir});
cmd.stderr.on('data', data => {
  console.log('[cmd; stderr]', data.toString());
});
const rl = createInterface({
  input: cmd.stdout,
  crlfDelay: Infinity,
  historySize: 0,
});
rl.on('line', data => {
  if (!line) return; // ignore empty lines, if any
  const file = join(dir, line);
  pushFileToAsyncQueue(file);
});
rl.on('close', () => {
  console.log('readline finished');
});
```

**Comment by isaacs** [comment]
In v9 this might be possible by bringing back the `nounique` option, so that it won't even try to cache anything persistently along the walk.  The caveat will be that:

- `glob()` and `globSync()` will always be a memory hog, because it's giving you an array of results, so there's no way to do that without storing the results.  But iteration or streams would work fine.
- You will get a few duplicate entries, if you use `**` or `..` with any degree of complexity, and don't have backpressure to slow down the stream.

Alternatively, we could preserve uniqueness and support walks of up to several million entries, by having the `seen` set only include the path string rather than the `Path` object.  This will impact performance a tiny bit, because the JS engine can hash objects uniquely in a Set much more efficiently than strings.

**Comment by isaacs** [comment]
https://github.com/isaacs/node-glob/issues/504#issuecomment-1452483201
