### ISSUE TITLE
Splitting the LICENSE file?

### ISSUE THREAD

**Issue by hyandell** [isaacs/node-glob#459]
Hi Glob folk,

I'm a part of the Open Source Program Office at AWS and wanted to let you know of a licensing painpoint. When pulling down updated npm packages, the glob package, and packages that include glob, always raise an eyebrow because of the CC-BY-SA license for the logo being mentioned. CC-BY-SA is a curious license for software, thus I get alerts to review. It's the more frustrating because the logo isn't included in the npm package file :)

I thought I'd share this because it's very unique to this project. "Oh, it's the glob text" might be something I mutter on a whole bunch of import-alerts :) I don't expect you to rate my pain highly, frankly the logo is awesome and it's great that it's being called out. But I did wonder if the license of the logo could move out into a separate LOGO-LICENSE file, which then isn't included in the npm package?

Apologies if this is too selfish a suggestion.

**Comment by isaacs** [comment]
Would it solve your problem if the CC-BY-SA was called out in the README.md but not in the license file?  Since it's not distributed with the code on npm, that seems like it'd be fine.  Though, I guess it _is_ distributed with the code via GitHub.  @tanyabrassie you own the copyright on that little guy, what's your thoughts?

**Comment by kellertk** [comment]
Hello glob people!

Another friendly AWS dev here - I'm unrelated to the team that validates licensing at AWS but I am a consumer of packages that consume glob as a dependency. For some more context, we have automated (and non-automated) systems that review open source licensing to make sure that we're in compliance, and because they're unusual for software, the Creative Commons licenses require manual review. Other packages (for example, [@vercel/ncc](https://github.com/vercel/ncc#readme)) are bundling glob's LICENSE file in their distribution, which is flagging the licensing exception - as well as any AWS package that includes glob as a first level dependency.  

I've created a simple PR (#463) that removes the information from the LICENSE file. Please let me know if this isn't appropriate.

**Comment by hyandell** [comment]
Thank you @isaacs and @tanyabrassie for being so understanding :)
