### ISSUE TITLE
Document breaking changes for `glob@8`

### ISSUE THREAD

**Issue by s100** [isaacs/node-glob#467]
It looks like `glob@8` has been released, congratulations! We would love to upgrade, but before that, would it be possible to document the changes, particularly the breaking changes, for this release, in the [change log](https://github.com/isaacs/node-glob/blob/main/changelog.md)? Thank you in advance.

**Comment by j0k3r** [comment]
Looks like it's only Node >= 12
https://github.com/isaacs/node-glob/commit/3d6c4cd2f3a6b7bdfdbf01fe9483badd5486fd71

**Comment by sircharlo** [comment]
> Looks like it's only Node >= 12 [3d6c4cd](https://github.com/isaacs/node-glob/commit/3d6c4cd2f3a6b7bdfdbf01fe9483badd5486fd71)

More than that, I believe... https://github.com/isaacs/node-glob/compare/v7.2.1...v8.0.1#diff-b95fa40c848afb412eab450be1e30c32066448f8401650cfddf7343d1aa7e133

**Comment by XhmikosR** [comment]
Yeah, and also https://github.com/isaacs/minimatch/compare/v4.2.1...v5.0.1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by isaacs** [comment]
The minimatch 5 breaking change is not a breaking change for glob, because it's _always_ coerced all slashes to `/`.  It's only a breaking change if you're using minimatch directly.  (And if you're relying on glob's minimatch behaving a particular way, and don't have a dependency on it yourself, well... that's not wise.)

But sure, I'll add a changelog.

**Comment by sircharlo** [comment]
Weird, my project completely broke with version 8. I must have misunderstood something.

**Comment by ath0mas** [comment]
I also had to change my patterns sent to `glob` when updating from v7.2 to v8.0, to not get empty array instead of correct list results.

On Windows, and mixing or joining _path_ values with "child" glob patterns, it works quite fine directly with v7.2, while with v8.0 you are required to replace backslashes with forward-slashes (basic replace, or like using [normalize-path](https://www.npmjs.com/package/normalize-path) or [unixify](https://www.npmjs.com/package/unixify) packages).

- does it come from the minimatch v3 to v5 update? (or v3.0 to v3.1 in unpublished 7.2.1 yet?)
if so, it should be added to the changelog.md I think
- even if the README mentions the "backslashes vs. forward-slashes" it in its [Windows section](https://github.com/isaacs/node-glob#windows), maybe it should be more explicit about how to manipulate _path_ values and meet the expected glob pattern "format" and/or the "tools" to help do so.

Sorry for the ref, but [fast-glob helped me understand](https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows) with its
> Use the [normalize-path](https://www.npmjs.com/package/normalize-path) or the [unixify](https://www.npmjs.com/package/unixify) package to convert Windows-style path to a Unix-style path.

**Comment by sircharlo** [comment]
I'm trying upath as we speak to see if that would work in my case. For sure a heads up would've been nice, as it worked before and is broken now for "\\" (read: non-UNIX) style paths.

**Comment by sircharlo** [comment]
> I'm trying upath as we speak to see if that would work in my case. For sure a heads up would've been nice, as it worked before and is broken now for "\\" (read: non-UNIX) style paths.

Confirmed, using upath as a drop-in replacement for path works great along with glob.

**Comment by larshp** [comment]
Also breaks stuff for me, probably due to windows paths as noted above.

**Comment by isaacs** [comment]
[This caveat] has been in the readme for a a decade now (added in 386f7e8).  But if someone has a repro case showing something that worked in v7 and doesn't work in v8, I'd be happy to take a look.

**Comment by larshp** [comment]
thanks

suggest adding a note about the caveat in the changelog, as the behavior changes from 7.2.0 to 8.0.0? My issue occurs in https://github.com/abaplint/abaplint/blob/main/packages/cli/src/file_operations.ts, however I have not taken the caveat into account, and also not debugged it, so its probably an issue in my library.

**Comment by domoritz** [comment]
The update broke widows support for me. Here is a repro case: https://github.com/vega/ts-json-schema-generator/pull/1221/.

**Comment by icebob** [comment]
Same issue here. On Windows, version 8.x.x doesn't find files in folder that works on 7.2.0

**Comment by juergba** [comment]
Upgrade to v8.0.1 breaks Mocha as well.

**Comment by nicolas377** [comment]
Using backslashes was never explicitly supported by glob, see the [windows portion of the README](https://github.com/isaacs/node-glob/#windows). My current solution is to resolve paths and then normalize them to forward slashes. See this example:

```js
// assuming the pattern is stored in string variable pattern, and that node's path module has been imported
const normalizedPattern = path.resolve(pattern).split(path.sep).join("/");
glob.sync(normalizedPattern);
```

The workaround will most likely change soon, assuming the implementation of #468 lands.

**Comment by JustinBeckwith** [comment]
Not to pile on, but this broke linkinator as well:
https://github.com/JustinBeckwith/linkinator/pull/389

Very specifically it changed something with paths on windows.  I'll dig in and try to get a more minimal repo.

**Comment by isaacs** [comment]
Just to repeat what was already said above:

- This is a change that occurred in a semver major.  It should not have broken anyone unexpectedly, unless you are depending on `*` or `>=` or something foolish like that.
- It is dropping support for a use case that has not been supported, explicitly in the readme, for 10 years.
- It _fixed_ the use of escape characters on Windows platforms (which _was_ broken before).

A v8 minor will come with the ability to explicitly choose to use `\` as a path separator _and not an escape character_ in #468.

Since `cwd` and `root` are always paths, and not patterns, we can add `/`-coercion to those automatically.

**Comment by JustinBeckwith** [comment]
Apologies, I used "broke" a tad flippantly :) The PR to update the dependency caused CI to fail in a way that wasn't obvious in the changelog.  Thanks for the detailed explanations!

**Comment by isaacs** [comment]
@JustinBeckwith No worries!  I definitely knew what you meant.  More just trying to forestall the next dozen comments complaining about glob breaking their programs 😅

**Comment by SimenB** [comment]
>More just trying to forestall the next dozen comments complaining about glob breaking their programs

I'd just like to say that's the most relatable comment I've ever seen on GitHub! 😅

Also - I appreciate the work you've done for the community, node and npm through the years. A major version breaking assumptions is not a huge issue.

Thank you! ♥️

**Comment by s100** [comment]
> * This is a change that occurred in a semver major.  It should not have broken anyone unexpectedly, unless you are depending on `*` or `>=` or something foolish like that.
> * It is dropping support for a use case that has not been supported, explicitly in the readme, for 10 years.
> * It _fixed_ the use of escape characters on Windows platforms (which _was_ broken before).

Would it be possible to document these changes in the [change log](https://github.com/isaacs/node-glob/blob/main/changelog.md)?

**Comment by ronenteva** [comment]
> Just to repeat what was already said above:
> 
> * This is a change that occurred in a semver major.  It should not have broken anyone unexpectedly, unless you are depending on `*` or `>=` or something foolish like that.
> * It is dropping support for a use case that has not been supported, explicitly in the readme, for 10 years.
> * It _fixed_ the use of escape characters on Windows platforms (which _was_ broken before).
> 
> A v8 minor will come with the ability to explicitly choose to use `\` as a path separator _and not an escape character_ in #468.
> 
> Since `cwd` and `root` are always paths, and not patterns, we can add `/`-coercion to those automatically.

You are 100% right, but why not mention it in the changelog?

**Comment by swrdfish** [comment]
Same issue came up on Windows for version 7.2.2 also. Was working fine with 7.2.0

**Comment by swrdfish** [comment]
@nicolas377 thanks! That worked.
