### ISSUE TITLE
7.2.3 pom.xml breaks things.

### ISSUE THREAD

**Issue by gunnar-ifp** [isaacs/node-glob#478]
minimatch dependency has been updated to [3.1.1,4), while in older versions it's [3.0.4,4).
This will break any project build that uses maven plugins that have dependencies like [3.0.2,3.1) in them. Say like org.webjars.npm:jshint:jar:2.11.0 which is used for example by the latest wro.isdc.wro4j:wro4j-maven-plugin:jar:1.10.1.
Not so good.

**Comment by nicolas377** [comment]
I'm not seeing the real problem here. Are you running into errors or unexpected behavior? If so, could you provide a reproduction case?

**Comment by nicolas377** [comment]
Also, the dependencies that you mention seem to be java dependencies, and you're using pom.xml for dependencies. node-glob is a package for node.js, not for java.

**Comment by isaacs** [comment]
Sorry, I have no idea what you're talking about, or how one would even go about installing this with Maven.

Please install this module using npm.  It's JavaScript, not Java.

If there is some existing build system that is breaking due to the changes in this library, please provide a reproduction case so I can understand what the issue is, and I will be happy to take a look at it.  But just to manage expectations, it sounds like you might be well outside of the supported use case, so the answer might be "sorry, that's a you problem".

**Comment by gunnar-ifp** [comment]
We are using the maven plugin ro.isdc.wro4j:wro4j-maven-plugin in version 1.10.1 in some legacy project.

This jar uses ro.isdc.wro4j:wro4j-extensions:jar:1.10.1, which uses org.webjars.npm:jshint:jar:2.11.0.
Now jshint uses org.webjars.npm:minimatch:jar with a version bracket of [3.0.2,3.1).
But it also uses org.webjars.npm:cli:jar:[1.0.0,1.1) which in turn uses org.webjars.npm:glob:jar:[7.1.1,8).

glob also uses minimatch but in the latest 7.2.3, which does fit in [7.1.1, 8), got a new version limit in the pom.xml of [3.1.1,4).
Since [3.0.2,3.1) and [3.1.1,4) are disjunct, maven gives up at that point.

Since it's apparently not you that released 7.2.3 to maven central, it's not your problem. That's ok, just in case some other people show up you know why. We solved it by manually forcing 7.2.0 as glob dependency for ro.isdc.wro4j:wro4j-maven-plugin.
