### ISSUE TITLE
Glob 7.2.0 -> 8.0.3 glob.sync returns different result, why?

### ISSUE THREAD

**Issue by fabiohaertel** [isaacs/node-glob#480]
Hi guys.

I'm using Windows with node 16.12 and npm 8.1.0

Couldn't figure this out by myself.
I have a simple scenario:

`npm i glob@7.2.0 `
```
const glob = require('glob');
const $path = require('path');

const files = glob.sync($path.join(__dirname, '*.txt'));
console.log(files)
```
Result = [ 'C:/DEV/glob/a.txt', 'C:/DEV/glob/b.txt' ]

`npm i glob@8.0.3 `
```
const glob = require('glob');
const $path = require('path');

const files = glob.sync($path.join(__dirname, '*.txt'));
console.log(files)
```
Result = []

Not sure what I should do here. Tried googling for some time but couldn't find an explanation.

Can anybody help me?
Thanks!

**Comment by nicolas377** [comment]
glob v8 updated minimatch, the library that does glob's matching, to v5. Minimatch v5 breaks windows glob matching by forcing all inputs to use forward slashes. Backslashes are considered escape characters. Since you're using the path module, it will automatically use backslashes for you since you're on windows. There are two solutions:
1. import `path/posix` instead of path
    -  that is a submodule of path that provides the *nix version of the path module. You will be able to use it just as you will `path`, but it will automatically use forward slashes
2. manually convert the string to use forward slashes
    - you could use `path.join(__dirname, '*.txt').split(path.sep).join("/")` to split by the separator the path module is using, and recreates the string using forward slashes.

**Comment by fabiohaertel** [comment]
Thanks for the explanation.
