### ISSUE TITLE
[Question] Glob for exclude 'node_modules', 'package.json', 'package-lock.json' and include all other files and folders

### ISSUE THREAD

**Issue by aldanchenko** [isaacs/node-glob#483]
Hello 👋 

Could someone help me with glob string? I need to exclude 'node_modules', 'package.json', 'package-lock.json' and include all other files and folders.

I tried something like this

`**/!(core|node_modules|.git|package.json|package-lock.json|style.css)/*.*`

But no success.

Thank you!

Best regards, 
Alex

**Comment by isaacs** [comment]
That string says "any number of path segments, then something other than (...), then a file with a `.` in it".  So it'll match `a/b/c/core/d/e.f`, because the `**` matches `a/b/c/core`, the `d` is not in the exclude list, and `e.f` matches the `*.*`.  But it _won't_ match, for example, `./x.y`, because there's no "something other than (...)" preceding it.

Maybe you want something like this? `./!(core|node_modules|.git|package.json|package-lock.json|style.css)/**`  That'd pick up all files and directories that do not _start_ with the listed path portions.

Or you could use combine it with an explicit `ignore` option, and do something like this:

```js
glob('!(core|node_modules|.git|package.json|package-lock.json|style.css)/**', { ignore: '**/(core|node_modules|.git|package.json|package-lock.json|style.css)/**' })
```

which would pull in all files everywhere, except those that match the exclude pattern (and avoid walking them at the first level, since you know that you'll be excluding those anyway).

**Comment by techsin** [comment]
what if you want to exclude a folder that is nested deeply

**Comment by isaacs** [comment]
@techsin what this mean? Just add the deeply nested folder to the exclude list?

**Comment by isaacs** [comment]
`glob('whatever', { ignore: '**/ignoreme/**' })`
