### ISSUE TITLE
Issue when implementing on cypress

### ISSUE THREAD

**Issue by rilham97** [isaacs/node-glob#488]
When I tried to use glob in Cypress 10.x.x I got an error message `"TypeError: this.fs.readdirSync is not a function"` is anyone can help?

**Comment by isaacs** [comment]
Glob will not work in environments that don't have access to the filesystem.  (Can't traverse directories if `fs.readdir` isn't a thing!)

Can you share more about the environment where you're trying to run glob?  It sounds like it's probably not on a server.

**Comment by PixlRainbow** [comment]
Encountering a similar issue when integrating with Cypress. The environment is a standard MacOS 12 Montery MacBook Pro, no containerisation, no virtualisation.

Cypress is a test suite that I am using to run regression tests to ensure that my website is able to create downloads correctly. However, although Cypress has the means to test for the presence of files on disk and is able to read the contents of those files, Cypress lacks the ability to test for dynamically generated file names.

Some responses on the Cypress GitHub issue tracker indicated that Glob should be used to collect the list of downloaded files with a matching naming scheme, before passing them to Cypress API to handle testing.

The situation is a bit complicated because Cypress operates in a "mixed mode" environment where some code executes in node.js, and some code within a browser sandbox, and it is difficult to tell when each scope is active.

**Comment by isaacs** [comment]
Yeah, you're just going to have to run the glob() command in an environment with a file system (or provide a suitable fs mock via the `fs` option, I suppose). I'm not very familiar with cypress, but I'd look for some way to mark some code as being server side only.
