### ISSUE TITLE
Update to minimatch 6

### ISSUE THREAD

**Issue by wouterdb** [isaacs/node-glob#490]
Currently, glob requires [minimatch `~=5.0.1` ](https://github.com/isaacs/node-glob/blob/3a5a70af353b163712ee1c142d293d7bf2a661cf/package.json#L23)

This prevents depending software to use minimatch 6

I make this issue to get notified when this is updated

**Comment by isaacs** [comment]
It'll be done as part of https://github.com/isaacs/node-glob/pull/489

I'm way down in a rabbit hole of making a path walking module that's (hopefully) as fast as JavaScript can be, replacing a ton of object-based caching logic with a general purpose linked list tree on uint32array slabs.

My first approach was ok, but still too slow, because it spent so much time (1) garbage collecting many small entry objects in the cache, and (2) string processing in path.resolve() calls. I'm almost done with a pretty nice general purpose pointer library, which makes it easy to build things like trees and linked lists in a general way, which will make this all a lot easier and hopefully much more performant. 

Once that's done, the bottleneck will probably be the actual string parsing, and if we want to go any faster at that point, it may require exploring a non-regexp based approach to the matching itself, which will mean that minimatch probably changes significantly anyway. We'll see.
