### ISSUE TITLE
RFE: add sort option (for walk/walkSync methods only)

### ISSUE THREAD

**Issue by markcellus** [isaacs/node-glob#497]
Hello, thanks for building this package! It appears that since V9, sorting is no longer supported. But previous versions were sorted in the same order of the files on the file system. What's the recommended way to get this default behavior back? Thanks in advance!

**Comment by msev** [comment]
Hi @markcellus, 

you can use `reduceRight` instead of `reduce`

**Comment by geekact** [comment]
`files.sort()` would help you.

**Comment by isaacs** [comment]
I could add a sort option, but it'd only be possible for the `walk()` and `walkSync()` methods. The streams and iterators just emit in a somewhat random order due to the parallelism in the algorithm.

**Comment by isaacs** [comment]
So the feature request is:

Add a `sort` option, which is a function that can be called with `results.sort(options.sort)`, and is only relevant to the `walk` and `walkSync` methods.

**Comment by isaacs** [comment]
Actually, looking into this, it's pretty inconvenient to get the types right, since the things being sorted can be either a Path object or a string, and TypeScript gets annoyed when you try to reference the object type within a property type.  So it could be done, but any sort method you pass in would have to accept `Path | string` as the arguments, and then verify that it's actually a string (when you already know it has to be).

Whereas, if you just do `(await glob('**')).sort((a, b) => number)` it knows that `a` and `b` are strings, because at that point, the return type is fixed.

This is definitely just better done as a one-liner by the caller.

**Comment by geekact** [comment]
By the way, `Array.prototype.sort()` will sort items according ASCII code sequence without callback function. So, I prefer not to use callback function here for path array.

**Comment by isaacs** [comment]
@geekact That doesn't work if you want to sort by something else, though, like locale comparison or dictionary order, or if you have Stats objects, sorting by modified time or something.

**Comment by markcellus** [comment]
Wow I didnt even realize this was the thread I started because the title was changed (was my actual post edited too? 😬). Could've just closed this issue and opened a new one for the feature request, because the new title makes it seems as though I requested this feature when I didnt 😃.

To clarify, I didnt necessarily mean this needed to be added to the codebase here. I guess I just wanted to know what everyone else did/would do given the situation. And some suggestions here are helpful, so thank you!

**Comment by isaacs** [comment]
Sorry for the confusion, @markcellus.  I often reword titles once the discussion makes its way to some intended action, so that I can scan the issues list faster and see what actually has to be done.  Whether you were requesting it or not, I did sort of think it was an idea worth pursuing, but it turned out that it's not actually a good idea, once looking closer at it, so I closed it.

**Comment by markcellus** [comment]
Yeah I guess my original submission was more of a "question" to open up a discussion rather than an "issue". No worries. Thanks for looking into it!
