### ISSUE TITLE
Move glob CLI to separate package?

### ISSUE THREAD

**Issue by voxpelli** [isaacs/node-glob#536]
Follow up to https://github.com/isaacs/node-glob/issues/320

As it is now, installing a module like [`@npmcli/map-workspaces`](https://www.npmjs.com/package/@npmcli/map-workspaces) that relies on `glob` now also pulls in `jackspeak` and it in turns pulls in `@isaacs/cliui` which in my current lock file also adds:

```
    "node_modules/@isaacs/cliui/node_modules/ansi-regex": {
    "node_modules/@isaacs/cliui/node_modules/ansi-styles": {
    "node_modules/@isaacs/cliui/node_modules/emoji-regex": {
    "node_modules/@isaacs/cliui/node_modules/string-width": {
    "node_modules/@isaacs/cliui/node_modules/strip-ansi": {
    "node_modules/@isaacs/cliui/node_modules/wrap-ansi": {
```

Not a major issue in my project really, but its a surprise when all one really wanted was `@npmcli/map-workspaces` and no CLI.

And in my case I got it because I use @webpro's [`knip`](https://github.com/webpro/knip) which in turn uses `@npmcli/map-workspaces`, which made it even more surprising.

I see that you @isaacs  had similar concerns in #320 but then changed your mind, but not sure why.

**Comment by isaacs** [comment]
Originally, I'd thought a glob cli wasn't needed, because there were existing packages that did that. But, it turned out, the existing packages seem to all be abandoned and/or way out of date, so it seemed like it might be a good idea to release an officially supported one.

I can split it into a separate package, but meh. The added deps are tiny compared to path-scurry and minimatch, and people seem to find it convenient to have it built into glob. If jackspeak was vendored, you probably would not have even noticed.

**Comment by voxpelli** [comment]
Thanks for your quick response and your thoughts, I'm happy with that and this issue will answer it for others as well then :)

**Comment by kilburn** [comment]
@isaacs: do note that several of the packages enventually pulled in by `jackspeak` are esm-only. Hence, due to having this dependency in `glob`, the setups that cannot work with esm-only packages break when updating.

I'm not saying this must get you to reconsider, but it is an important point to take into account :)

**Comment by isaacs** [comment]
@kilburn Sure, but, it only pulls in the esm-only packages when loading via `import`, and the `engines` specification should restrict it to versions of node that can handle exports forking. What setups is this a problem? I'm open to workarounds, if any exist.

**Comment by kilburn** [comment]
In my case jest started crashing due to the esm-only packages (string-width / strip-ansi). This is because jest-cli used older versions of those that were not esm-only yet. With your update requiring the newer versions, yarn decided to use these newer ones for jest-cli too, leading to an instant crash when calling jest.

I worked around this by forcing the older versions through package.json resolutions rules.

**Comment by isaacs** [comment]
> yarn decided to use these newer ones for jest-cli too

Ok.  So.

In my opinion (and I have spent a fair bit of time on this subject) a package manager's most important job -- you could argue, it's _only_ job -- is to provide dependencies according a program's stated dependency contracts. Every time I bump the major version of something with a breaking change, I see issues reported by Yarn users because their package manager served invalid versions of dependencies. No warnings, no install errors, just a crash at runtime.

Seriously, like, we designed a whole module system and package manager in specifically to make this a solved problem, since way back in 2011. Just use npm. It's done this one job correctly forever. Since npm v7, you can even keep using a yarn.lock file, and it'll update it properly, with a correctly resolved dep tree. It's fast, it's reliable, and it actually does its one job.

Or, idk, if npm is just gross to you, maybe there's some newer version of yarn that doesn't have this problem that you could upgrade to? I never hear this problem from pnpm users, you could also give that a try? Even if you have a workaround for this one case, I can pretty much guarantee it'll bite you again at some point eventually. Your package manager is not doing it's job, you should definitely fire it or fix it.

**Comment by Sytten** [comment]
I mean JS package managers do suck because they don't have the concept of features.
There is really no need to pull the dependency `jackspeak` if I am never going to use it, it only increases your supply chain risk and liabilities around licensing.
In that sense the CLI should be a different package.
