### ISSUE TITLE
Cannot read properties of undefined (reading 'withFileTypes')

### ISSUE THREAD

**Issue by heartforit** [isaacs/node-glob#538]
Hi my friend,

just wanted to let you now that code on current version from npm "^10.3.2" has this beauty in it which leads to the error message given in the title:

node_modules\glob\dist\cjs\src\glob.js:65:37
```
    constructor(pattern, opts) {
        this.withFileTypes = !!opts.withFileTypes;
```

If you call ``const g = new Glob("./data/whatever/*.json")`` without options param, it leads to this error.

Kind regards.

**Comment by heartforit** [comment]
Could be prevented with  ``constructor(pattern, opts = {}) {``

**Comment by isaacs** [comment]
Yeah, the options param is required for proper TypeScript behavior.  That's how it infers the match type, by detecting whether `withFileTypes` has been provided. If it's defaulted to `{}` then you could do `new Glob<{ withFileTypes: true }>(pattern)` and TypeScript would think it's in `withFileTypes` mode but it actually wouldn't be. And since the template type can't be detected at run-time, there's no way to provide a default that is guaranteed to match the template type. That's why TypeScript doesn't allow defaults for arguments that are set as template types, unless the default is a valid instance of every possible template type.
<img width="1167" alt="Screenshot 2023-07-08 at 14 42 22" src="https://github.com/isaacs/node-glob/assets/9287/15fd96f4-0146-427c-9925-802dd6c87a99">

**Comment by heartforit** [comment]
Yeah, I see. thanks for your detailed reply. My ticket wasn't meaned to bother you anyhow. I suspected its connected to typescript.
Thanks for still comming back to me, I tought it will be dismissed in the first place, but was surprised that I got teached some stuff. Thanks mate. Keep it up.

**Comment by isaacs** [comment]
Don't worry at all, nothing in your request was bothersome. I'm happy to share, you're way more polite than you need to be 😅
