### ISSUE TITLE
Feature Request: Get star substitution values

### ISSUE THREAD

**Issue by RebeccaStevens** [isaacs/node-glob#539]
Essentially RegExp substitutions but for globs.

For example, with the regex `/abc(.*)xyz/` matched against `"abc123456xyz"`, the result has a value that corresponds to the string match by `(.*)` (ie. `$1` is `"123456"`).

I'd like to be able to do the same thing for globs.
So if I have the glob pattern `"abc/*/xyz"` which finds `"abc/123/xyz"` and `"abc/456/xyz"`, I'd like to be able to easily extract out the `*` substitution from each result. (e.g. `$1` is `123` for `"abc/123/xyz"`).

Sorry if this already exists, I didn't see it documented anywhere.

**Comment by isaacs** [comment]
This has been requested a few times, and I can certainly understand that it'd be useful.

However, for matching glob patterns, which don't really have any clear semantics for capture groups, and especially given how aggressively node-glob and minimatch are tuned for performance, it is quite challenging to figure out how to go about doing.

For very simple cases, with a single pattern with simple magic bits, like those mentioned here, it'd be somewhat straightforward. When walking the pattern, we'd just have to keep track of whether a regexp matched a path portion, and put it into an array whenever that happens.

It gets a bit more complicated when the patterns aren't as simple as just `*` matching an entire path portion.  For example, if you had `abc/*foo*/xyz`, which matches against `abc/barfoobaz/xyz`, you'd probably want the match results to be `['bar', 'baz']`, right? But, in practice, that `*foo*` is turned into a single regexp, so it'd mean using capture groups when we build the regexp. Fair enough, minimatch already wraps things in parens for most patterns, it just uses `(?: ... )` groups to _prevent_ capturing, because performance. So there'd be a somewhat tricky process of figuring out exactly which groups should be treated as captures, and which remain uncaptured, as in some cases we have to nest quite a few groups in order to implement dot-matching semantics, meaning a glob like `*(?)` turns into this:

```
/^(?:(?:(?!\.)[^/])(?:(?!(?:^|\/)\.\.?(?:$|\/))[^/])*?)?$/
 | |              | |                        | |     |
 | |              | |                        | ^^^^^^^-- then dots allowed
 | |              | ^^^^^^^^^^^^^^^^^^^^^^^^^^-- rest cannot be . or .. only
 | ^^^^^^^^^^^^^^^^-- first instance cannot start with .
 ^-- start of pattern
```

So in a case like that, the entire thing would have to be captured, I guess?  But when dealing with nested extglobs and many patterns together, it can be a bit convoluted.

A glob pattern matches a _bunch_ of things, so it's not just like a RegExp, where you have a single string and a set of captures in that one string.  So we'd need a capture set for every match that is found.  Ie, if `abc/*/foo` expands to `['abc/x/foo', 'abc/y/foo']` you'd need two capture sets, like `[['x'], ['y']]`.

Globstar patterns like `a/**/b` that can match `a/b`, `a/x/b`, or `a/x/y/z/b` would be a bit challenging implementation-wise, because globstar is handled somewhat differently than the other single-path-portion matchers, since it needs to fork the process and test without the globstar, with the sub-path without the globstar, and with the subpath _with_ the globstar, to walk down the tree. In each globstar process, it'd need to keep track of where it started globstar-matching which is doable, but not a thing it's doing right now, and would involve additional moving parts.

Lastly, while all of that is just "more work than it seems", but not particularly difficult to work out how to do, where the semantics are probably most challenging, is with patterns where it's not clear _which_ portion should be the "match".  For example, if you have something like `a/**/*/**/b`, minimatch will note that that's equivalent to `a/*/**/b` and remove the first globstar. So if that matches `a/x/y/z/b`, what should the match results look like?  Any of `['x', 'y', 'z']`, `['', 'x', 'y/z']`, or `['x/y', 'z', '']` are defensible.

So, where I usually land on this is, "glob is a file path expander, not a general purpose string matcher, use RegExp if you want capture groups, sorry".

**Comment by isaacs** [comment]
Just to add a bit of salt on it, minimatch also converts `<start>/**/*/<rest>` to `<start>/*/**/<rest>`, because globstars are less costly if they occur later in the pattern, and single-star patterns are fast-pathed, so you could have a confusing case where it looks like your `*` matched multiple path portions, and your `**` only matched one.

And there are some cases where we have some known race conditions if multiple patterns can match a single path. Right now, we can just say "oh, that path already matched, skip it" when we encounter that, but if you're depending on the captures being reasonable, that is no longer an option. Consider a pattern like `a/{**/c,c/**}/d`. As it currently works, when considering the path `a/c/d`, only one of those two patterns `a/**/c/d` or `a/c/**/d` will actually be tested, and there are situations where the ordering of them is dependent on filesystem response times, so it's actually nondeterministic. That's fine, as long as it doesn't matter _how_ a path matched, only whether it did or not.
