### ISSUE TITLE
Way to stop traversal after match?

### ISSUE THREAD

**Issue by httpete** [isaacs/node-glob#544]
I am making a node_modules cleaner, and there are multiple levels of node_modules folders all through my project. I just want to stop traversing if it finds a match, because I will be deleting them and having glob traverse down just adds more.

right now I am globbing for **/node_modules

Thank you very much for looking at this question. We rely on glob here for many things and it's fantastic.

**Comment by isaacs** [comment]
Hm, this is a good question.  There isn't really a way to do this right now.  You can _sort of_ get close to it if you're iterating rather than just fetching the list, since if you stop consuming the iterator, then the stream will get backpressured and pause, but it'll still keep looking until the _next_ match, so it's not quite what you're looking for.  In fact, if you delete `x/node_modules` while iterating, and when you delete it, it's in the process of finding `x/node_modules/y/z/node_modules`, then there's a chance you'll even end up raising errors as it keeps trying to walk over a directory tree that no longer exists.

I think some sort of option to say "do not look for matches that are children of a match" would be what you need, and should be possible to do. My first thought was "oh, just use rimraf(), since it expands globs already" and then realized, yeah, rimraf has exactly this problem, and will do a bunch of unnecessary work in that case, just like you're describing. Like, if you do `rimraf('a/**')` then it first makes a list of every folder and file under `a`, and then recursively deletes each of them, but since the first one it deletes is `./a`, it's just going to be getting ENOENTs for all the rest, which is potentially a lot of extra syscalls just to make sure it's really super deleted 😅

**Comment by isaacs** [comment]
Tested this out with iterators, it actually will work as you want if you do it synchronously, since then you can delete it before `glob` has a chance to readdir (or rather, the `readdir` will raise ENOENT, and it'll just abandon that branch of the search).

```console
$ mkdir -p {b,c,d}/{b,c,d}/{c,d,e}/{c,e,f}

$ node
Welcome to Node.js v18.16.0.
Type ".help" for more information.
> const rimraf = require('rimraf'); const glob = require('../'); const it = glob.iterateSync('**/c'); for (const f of it) { console.log(f); rimraf.sync(f) }
c
d/c
b/c
d/d/c
d/b/c
b/d/c
b/b/c
d/d/e/c
d/d/d/c
d/b/e/c
d/b/d/c
b/d/e/c
b/d/d/c
b/b/e/c
b/b/d/c
true
>
```

However, in the async case, you do potentially get one extra match returned, because it does the `readdir` before emitting the match on the async iterator, so there's a race there:

```console
$ mkdir -p {b,c,d}/{b,c,d}/{c,d,e}/{c,e,f}

$ node
Welcome to Node.js v18.16.0.
Type ".help" for more information.
> const rimraf = require('rimraf'); const glob = require('../'); const it = glob.iterate('**/c'); for await (const f of it) { console.log(f); await rimraf(f) }
c
d/c
b/c
c/c  <<<<<<<<----- extra match, unnecessary rimraf
d/d/c
d/b/c
b/d/c
b/b/c
d/d/e/c
d/d/d/c
d/d/c/c
d/b/e/c
d/b/d/c
b/d/e/c
b/d/d/c
b/b/e/c
b/b/d/c
undefined
>
```

**Comment by httpete** [comment]
Thanks for the investigation @isaacs but I don't use rimraf just glob. Maybe this is the only case to have this recursive N level repetition, as clearly only a machine would do such a thing.

**Comment by isaacs** [comment]
Right, however you're deleting the folders though, if you do it synchronously in a sync iterator, you're not going to get any extras. Otherwise, yes, it'll find extra subfolder matches.

It's probably possible to get glob to have an option to omit any matches that are children of other matches, but it's not high on my todo list. Patch welcome if anyone wants to take a run at it.

**Comment by isaacs** [comment]
While it's not quite exactly what you're asking for, `includeChildMatches: false` did just land in version 10.2.

This is a best effort kind of thing; it just adds each match as an ignore once encountered. But if you `glob(['a/b/c/d/e', 'a/**'], {includeChildMatches: false})`, then `'a/b/c/d/e'` will be emitted as a match before its parent is encountered, so it'll still be included, even though its parent is in the result set.
