### ISSUE TITLE
v10.3.7 is broken

### ISSUE THREAD

**Issue by Zippanova** [isaacs/node-glob#558]
Had a heck of a time figuring out why my CI/CD pipeline broke today with no changes since last week.  It looks like I was grabbing the latest package of `blob` published in npm (v10.3.7) and getting this error (note: using TS here): 

```
error TS2307: Cannot find module 'glob' or its corresponding type declarations.

import { glob } from 'glob'
                     ~~~~~~
```

I downgraded to v10.3.6 and this works without errors.  It appears this [related commit](https://github.com/isaacs/node-glob/commit/1d3fdd22d4f398abe32d344a69fce27207d59cab) is failing some GitHub checks as well.  Just thought you'd like to know. :slightly_smiling_face:

**Comment by jmjones-ping** [comment]
Same here for a TS project. 

`import { globSync } from 'glob'`
`error TS2724: '"glob"' has no exported member named 'globSync'. Did you mean 'GlobSync'`

10.3.6 fixes it for me as well @Zippanova

**Comment by isaacs** [comment]
https://github.com/isaacs/node-glob/issues/557

It's not broken. It just stopped incorrectly advertising its types. Please enable `packageJsonExports` in your tsconfig, so that you will get the correct types for this module, which you weren't getting before.

**Comment by Zippanova** [comment]
Hmm, I did not find any release notes for this version related to this change.  Thanks for the tip!

**Comment by isaacs** [comment]
I don't usually bother with release notes for patch versions, because nothing changed in the interface contract.

**Comment by jmjones-ping** [comment]
Definitely thankful for the package - but please just realize even restoring things to the way they are supposed to be causes significant rework for some of us - especially in larger repos.

We're on a typescript version where `packageJsonExports` isn't available and in a monorepo, so we're stuck updating everything and testing, which I wouldn't really expect in a patch release update.

Thanks for sharing all the threads that share the reasoning as that makes since, but just wanted to share a bit why some of us are a bit surprised by the patch version update.

**Comment by isaacs** [comment]
@jmjones-ping It is never fun to learn that there's been a subtle bug lying in wait threatening to cause undefined behavior at run time, or process gaps where you are on the bleeding edge of one piece but unmaintained legacy versions of another. I'm sensitive to the surprise and frustration, and also glad that you found out this way, rather than another. 

If you are using a very old typescript version (or node, express, react, etc, any significant platform dep), I strongly recommend pinning all dependencies and being extremely cautious about any upgrades, until you can update the platform dep to a current supported version. Most library authors do current work on current platform versions, and expect that they are configured correctly in order to behave correctly.
