### ISSUE TITLE
New version jackspeak break commonjs libs

### ISSUE THREAD

**Issue by udarrr** [isaacs/node-glob#563]
Hi @isaacs could you move changes regarding new version of jackspeak to 11 version because it require ESM modules, and revert previous one 2.0.3 for 10

**Comment by isaacs** [comment]
Can you clarify what is breaking and in which contexts?

I use glob 10 in many commonjs modules, it works fine.

**Comment by udarrr** [comment]
Yes sure, generally it's because of strip-ansi 7.0.1 it's ESM currently. Dependencies from top to bottom are got->jackspeak->@isaacs/cliui->strip-ansi.
Yes it works with versions until 10.3.7 but not with the latest

**Comment by isaacs** [comment]
What are you installing/running with? It works with node and npm.

**Comment by udarrr** [comment]
Let my explain. One of your dependency is being used strip-ansi since version 7.0.0 has been converted to ESM https://github.com/chalk/strip-ansi/commit/7cda68dcadde18b19bfa31b6223e9f0e60b3e319 the dependency has been included to @isaacs/cliui. It's some kind of breaking changes and can't be used for packages with commonjs approach.

**Comment by isaacs** [comment]
@udarrr Trust me, I am fully aware of what packages are being used.

Jackspeak depends on @isaacs/cliui, which depends on:

```
    "strip-ansi": "^7.0.1",
    "strip-ansi-cjs": "npm:strip-ansi@^6.0.1",
```

What this does is that it tells npm (or any package manager that understands this syntax, which has been in npm for a _very_ long time at this point, dating back to npm version 4, iirc) to install the version 7 of strip-ansi in `node_modules/strip-ansi`, and install version 6 of strip-ansi in `node_modules/strip-ansi-cjs`.

At run time, the cjs implementation of @isaacs/cliui does this, in `build/index.cjs':

```js
const stripAnsi = require('strip-ansi-cjs')
```

and the ESM implementation in `index.mjs` does this:

```js
import stripAnsi from 'strip-ansi'
```

The module that gets loaded depends on whether you use `import` or `require` to load it, by referencing the `package.json`'s `exports` field:

```json
{
  "exports": {
    ".": [
      {
        "import": "./index.mjs",
        "require": "./build/index.cjs"
      },
      "./build/index.cjs"
    ]
  }
}
```

This works with CommonJS, and it works with ESM, provided that you are using a package manager that is up to date and complete, and a node version since node 12.

That's why I asked, what are you installing and running it with?

Because I think you are using a broken package manager, and that is the problem.  Usually when people report these sorts of problems, it's because they are using yarn version 1.  If that's what you're using, I suggest you stop doing that.

**Comment by udarrr** [comment]
Hi @isaacs yes you are right... Thank you for the clarification!
