### ISSUE TITLE
Are there return value examples for versions 7.1.6 and 10 glob.sync

### ISSUE THREAD

**Issue by haaaafgdbar** [isaacs/node-glob#565]
Version 10 glob.sync return value format is inconsistent each time, not sure what caused it. Any examples

**Comment by haaaafgdbar** [comment]
sorry, the problem I just described is wrong, version 10 of glob.sync does not return the same result every time. But I used glob.sync 7.1.6 to return the same result every time. So I'm not sure if it's an OS issue or a version issue

**Comment by isaacs** [comment]
Do you have an example you can share where `globSync` returns different results each time? That should definitely not happen, unless the file system changes while the search is being performed.

**Comment by isaacs** [comment]
I've tried reproducing this with a variety of patterns in the benchmark fixtures used by this project, and can't find a case where `globSync` produces different results between runs. Different _order_ of results, yes, but the same results are returned every time.

Happy to re-open if a reproduction case can be provided, otherwise closing to remove it from my todo list.
