### ISSUE TITLE
Performance order of magnitude slower than native

### ISSUE THREAD

**Issue by joliss** [isaacs/node-glob#78]
For patterns like `**/*.txt`, `node-glob` seems to be an order of magnitude slower than native globbing.

Here is a script to demonstrate this (save it as `node-glob/benchmark.sh`): https://gist.github.com/joliss/7469304

Here are the timings from [running this on my system](https://gist.github.com/joliss/7469324):
- Bash timing: 0m0.696s
- Node statSync and readdirSync timing: 0m0.977s
- Node glob.sync timing: 0m9.676s
- Node glob async timing: 0m22.130s (fluctuating somewhat)

Based on the recursive statSync + readdirSync performance, it seems that it should be _possible_ to make node-glob nearly as fast as native, at least for simple patterns.

This is an actual issue for me, with sets of only a few hundred files: In a JavaScript build tool I'm writing, the execution time of the most performance-critical code path is currently bottlenecked on `node-glob`. I know I could avoid using `node-glob` if I wanted to, but I'd love to expose globbing syntax in my tool's API.

I'm guessing that there are two possible sources for this slowness:
- Duplicate stat or readdir calls (related: #76)
- The pattern matching burns too many CPU cycles (perhaps [minimatch](https://github.com/isaacs/minimatch) is the culprit)

If someone wants to dig into this and figure out what's going on, you'd be my hero!

If it's technically hard to fix this, I'd also like to find out sooner rather than later, because it means that I maybe shouldn't rely on globbing in my tool's API.

**Comment by joliss** [comment]
Yay! Thanks @isaacs :)

**Comment by bpasero** [comment]
This is some good reading how to implement fast file traversal in node.

@isaacs you wrote:

> Except in extremely rare scenarios, async fs I/O will always be strictly slower than sync fs I/O. If you don't need to be doing many things in parallel, there is no benefit.

I am not sure I follow, isn't async always faster because you can process directories in parallel which is happening a lot when recursing down a file system structure? Using sync APIs might be faster per method call but will always pay the penalty of sequential processing.

**Comment by isaacs** [comment]
@bpasero Even if you do the file actions asynchronously, there is usually a limit to just how async the fs can be, and there is a hard limit to how many threads node will use to perform async fs operations.  (Once upon a time that was 4, but I recall it being increased, maybe there's a cleverer heuristic involved since last I saw that code, which was a few years ago.  It might not be as "hard", but there is still definitely a limit.)

So, if you are parallelizing more fs ops than node allocates threads, it's going to back up, and be effectively serialized anyway.  (Of course, "serialized" with multiple parallel tracks, as each thread finishes what it's doing and then takes on a new job.)

However, all of this is ultimately limited by the file system itself!  Spinning disks can only be in one position, so if you're trying to read 2 files in parallel, the fs will either thrash (making both operations slower than they would've been), or make one operation wait for the other.

Stat and readdir calls are less thrashy and more cacheable by the fs, since they're only dealing with the file link table (at least, on most Unixy systems).  But in fact, if every bit of data is available in the operating system's fs cache, they'll be very fast, and adding the async thread management overhead will be relevant.

"Parallelizing" operations on a single machine (whether that's a single cpu or a single disk) is more like "multitasking" than "teamwork".  When you parallelize things across a _network_, of course, it's a whole different story, which is why things like Hadoop are so great for massively big data problems, compared with writing a simpler program for a single machine.  But when you parallelize a bunch of operations that are effectively throttled by a single bit of hardware, as a general rule, you're almost certainly not going to make things faster.

Lots of qualifiers there.  It's highly dependent on a lot of factors, like what specific type of disk is involved, the operating system, the file system type, as well as just whatever else the machine happens to be doing at the time.

If you _are_ doing many things in parallel (for example, it's a web server, where you don't want to pause in replying to one user's HTTP request while you read a file for another user), then async is absolutely the way to go.  Node makes this the "default" path because it's designed for building network programs, where this usually matters.

If you're a web server, then providing users with a consistently fast connection pick-up, and a predictable first-byte time, is all that really matters.  The "average file read time" is 100% worthless as a metric, if you lost business because some unlucky user had to wait 2s for a web page to load, and decided to hit the back button.

But if you're a cli utility, especially one that doesn't make network requests, then the situation is completely reversed.  The better approach is to avoid thrashing the disk, and since you have exactly one user who is going to wait for every single task to be completed, reducing the average task time is the way to go, so sync isn't just _easier_, it's also _better_.

**Comment by bpasero** [comment]
Yes, I also think it depends on the scenario and especially depends on what kind of complexity the code has that runs for each file node that is traversed. If all you do is just walking through the file system, I would not expect sync to be much slower than async. However, if for each node, there is some task happening that eats CPU cycles, being able to "offload" further traversing to other threads has a high performance impact.

I would assume node-glob would perform faster with async fs operations because for each path it needs to run its "glob" logic that potentially slows down the next fs call when done in sync.

**Comment by isaacs** [comment]
> If all you do is just walking through the file system, I would not expect sync to be much slower than async.

What I'm saying is that your expectation is wrong. You should expect sync to be *faster* than async.  Async is always slower, it just has less of an effect on slowing down *other* things (servers etc.)

**Comment by bpasero** [comment]
@isaacs well that is not what I see when I give it a try. 

* node v4.2.3
* MBP 10.11
* test folder: https://github.com/Microsoft/TypeScript.git

**traverse-async.js**
```javascript
var fs = require('fs');
var path = require('path');
var walk = function (dir, done) {
    var results = [];
    fs.readdir(dir, function (err, list) {
        if (err) return done(err);
        var pending = list.length;
        if (!pending) return done(null, results);
        list.forEach(function (file) {
            file = path.resolve(dir, file);
            fs.stat(file, function (err, stat) {
                if (stat && stat.isDirectory()) {
                    walk(file, function (err, res) {
                        results = results.concat(res);
                        if (!--pending) done(null, results);
                    });
                } else {
                    results.push(file);
                    if (!--pending) done(null, results);
                }
            });
        });
    });
};

walk('/Users/bpasero/Development/Microsoft/typescript', function (err, results) {
    if (err) throw err;
    console.log(results.length);
});
```

**traverse-sync.js**
```javascript
var fs = require('fs');
var path = require('path');
var walk = function (dir, done) {
    var results = [];
    var list = fs.readdirSync(dir);
    var pending = list.length;
    if (!pending) return done(null, results);
    list.forEach(function (file) {
        file = path.resolve(dir, file);
        var stat = fs.statSync(file);
        if (stat && stat.isDirectory()) {
            walk(file, function (err, res) {
                results = results.concat(res);
                if (!--pending) done(null, results);
            });
        } else {
            results.push(file);
            if (!--pending) done(null, results);
        }
    });
};

walk('/Users/bpasero/Development/Microsoft/typescript', function (err, results) {
    if (err) throw err;
    console.log(results.length);
});
```

Results after a fresh OS restart:

```
~/Desktop/traverse-fs> time node traverse-async.js 
29868

real	0m0.653s
user	0m0.401s
sys	0m0.790s


~/Desktop/traverse-fs> time node traverse-sync.js 
29868

real	0m1.176s
user	0m0.340s
sys	0m0.505s
```

**Comment by trevnorris** [comment]
@bpasero These tests are hard to do well. Think like type of hardware (platter or ssd), has your OS cached the paths, etc. can give drastically different results. For example, here are my results using your scripts:
```
trevnorris:node (throw-mc-fix) $ \time ./out/node-latest /tmp/walk-sync.js
212765
3.36user 1.22system 0:04.55elapsed 100%CPU (0avgtext+0avgdata 111380maxresident)k

trevnorris:node (throw-mc-fix) $ ^C
trevnorris:node (throw-mc-fix) $ \time ./out/node-latest /tmp/walk-async.js
212765
9.04user 3.06system 0:08.26elapsed 146%CPU (0avgtext+0avgdata 514980maxresident)k
```
As you can see, much different than yours.

**Comment by bpasero** [comment]
Right, I have seen varying results even after restarts too.

I do like the statement that using async fs methods will prevent blocking code from executing if there are computational things happening per node. That is my reason for sticking with async for now.

Btw I find it interesting that Python seems to care about file traversal performance enough that they added a function for it (os.scandir): https://www.python.org/dev/peps/pep-0471/

**Comment by anurbol** [comment]
`glob.sync("**/foo.ts", {exclude: ["**/node_modules/**"]})` shows surprising execution time like 12-15 sec for a directory with 70000 files, 15000 dirs. Is it ok? 
Windows 10, node 12.4
